-- Аккаунты игроков. username — как ввёл игрок, username_key — в нижнем регистре для уникальности.
CREATE TABLE account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(20)              NOT NULL,
    username_key  VARCHAR(20)              NOT NULL UNIQUE,
    password_hash VARCHAR(100)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Входы. Храним не сам токен, а его SHA-256: утечка базы не даёт войти чужим аккаунтом.
CREATE TABLE auth_session (
    token_hash VARCHAR(64)              PRIMARY KEY,
    account_id BIGINT                   NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX auth_session_account ON auth_session (account_id);
