-- Сыгранные до конца партии. Брошенные (сервер перезапустился посреди игры) сюда не попадают.
CREATE TABLE finished_game (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id      VARCHAR(16)              NOT NULL,
    started_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    player_count INT                      NOT NULL
);

-- Участники партии и их места: 1 — победитель, дальше — в обратном порядке выбывания.
CREATE TABLE game_participant (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id    BIGINT  NOT NULL REFERENCES finished_game (id) ON DELETE CASCADE,
    account_id BIGINT  NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    place      INT     NOT NULL,
    winner     BOOLEAN NOT NULL,
    UNIQUE (game_id, account_id)
);

CREATE INDEX game_participant_account ON game_participant (account_id);
